// -*- C++ -*- generated by wxGlade 0.3.5.1 on Sat Jan 15 17:29:02 2005

#include <wx/wx.h>
#include <wx/image.h>

#include "xtnDialogDiffCurrent.h"

#ifndef XTNDIALOGDIFFDUAL_H
#define XTNDIALOGDIFFDUAL_H

// begin wxGlade: dependencies
// end wxGlade


class xtnDialogDiffDual: public wxDialog {
public:
    // begin wxGlade: xtnDialogDiffDual::ids
    enum {
        BT_BROWSE_WITH = 1017,
        BT_BROWSE_AFTER = 1018,
        BT_DIFF = 1019,
        BT_CANCEL = 1020
    };
    // end wxGlade

    xtnDialogDiffDual(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: xtnDialogDiffDual::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: xtnDialogDiffDual::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticText* lbTitle;
    wxStaticText* lbWith;
    wxTextCtrl* txWith;
    wxButton* btBrowseFile;
    wxStaticText* lbAfter;
    wxTextCtrl* txAfter;
    wxButton* btAfterBrowse;
    wxStaticText* lbIds;
    wxTextCtrl* txIds;
    wxStaticText* lbIgnore;
    wxTextCtrl* txIgnore;
    wxCheckBox* cbBeforeValues;
    wxStaticText* lbSep;
    wxTextCtrl* txSep;
    wxCheckBox* cbTagChilds;
    wxButton* btDiff;
    wxButton* btCancel;
    // end wxGlade

protected:
	// - Actions
	void OnDiff(wxCommandEvent &event);
	void OnCancel(wxCommandEvent &event);
	void OnBrowseWith(wxCommandEvent &event);
	void OnBrowseAfter(wxCommandEvent &event);
	// - Déclaration de la table
    DECLARE_EVENT_TABLE()

public:
	wxString getBeforeFile() { return txWith->GetValue(); }
	wxString getAfterFile() { return txAfter->GetValue(); }
	DEFINE_setDlgOptions;
	DEFINE_getDlgOptions;
};


#endif // XTNDIALOGDIFFDUAL_H
